//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoComplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poblacion
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> Poblacion1 { get; set; }
    
        public virtual Poblacion Poblacion11 { get; set; }
        public virtual Poblacion Poblacion2 { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
